// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlite

import (
	"database/sql"
	"time"
)

type AppMetum struct {
	Key   string
	Value string
}

type Session struct {
	ID        string
	UserID    string
	TokenHash string
	ExpiresAt int64
	RevokedAt sql.NullTime
	CreatedAt time.Time
}

type User struct {
	ID           string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
}
