// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlite

import (
	"context"
	"database/sql"
)

const claimMachineJob = `-- name: ClaimMachineJob :execrows
UPDATE machine_jobs
SET status = 'running',
    lease_owner = ?1,
    lease_until = ?2,
    updated_at = ?3
WHERE id = ?4
  AND status = 'queued'
`

type ClaimMachineJobParams struct {
	LeaseOwner sql.NullString
	LeaseUntil sql.NullInt64
	UpdatedAt  int64
	ID         string
}

func (q *Queries) ClaimMachineJob(ctx context.Context, arg ClaimMachineJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimMachineJob,
		arg.LeaseOwner,
		arg.LeaseUntil,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createMachine = `-- name: CreateMachine :exec
INSERT INTO machines (id, name)
VALUES (?1, ?2)
`

type CreateMachineParams struct {
	ID   string
	Name string
}

func (q *Queries) CreateMachine(ctx context.Context, arg CreateMachineParams) error {
	_, err := q.db.ExecContext(ctx, createMachine, arg.ID, arg.Name)
	return err
}

const createMachineState = `-- name: CreateMachineState :exec
INSERT INTO machine_states (machine_id, status, desired_status, updated_at)
VALUES (?1, ?2, ?3, ?4)
`

type CreateMachineStateParams struct {
	MachineID     string
	Status        string
	DesiredStatus string
	UpdatedAt     int64
}

func (q *Queries) CreateMachineState(ctx context.Context, arg CreateMachineStateParams) error {
	_, err := q.db.ExecContext(ctx, createMachineState,
		arg.MachineID,
		arg.Status,
		arg.DesiredStatus,
		arg.UpdatedAt,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, user_id, token_hash, expires_at)
VALUES (?1, ?2, ?3, ?4)
`

type CreateSessionParams struct {
	ID            string
	UserID        string
	TokenHash     string
	ExpiresAtUnix int64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAtUnix,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, email, password_hash)
VALUES (?1, ?2, ?3)
`

type CreateUserParams struct {
	ID           string
	Email        string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.ID, arg.Email, arg.PasswordHash)
	return err
}

const createUserMachine = `-- name: CreateUserMachine :exec
INSERT INTO user_machines (user_id, machine_id, role)
VALUES (?1, ?2, ?3)
`

type CreateUserMachineParams struct {
	UserID    string
	MachineID string
	Role      string
}

func (q *Queries) CreateUserMachine(ctx context.Context, arg CreateUserMachineParams) error {
	_, err := q.db.ExecContext(ctx, createUserMachine, arg.UserID, arg.MachineID, arg.Role)
	return err
}

const deleteMachineIfNoUsers = `-- name: DeleteMachineIfNoUsers :exec
DELETE FROM machines
WHERE id = ?1
  AND NOT EXISTS (
    SELECT 1
    FROM user_machines um
    WHERE um.machine_id = machines.id
  )
`

func (q *Queries) DeleteMachineIfNoUsers(ctx context.Context, machineID string) error {
	_, err := q.db.ExecContext(ctx, deleteMachineIfNoUsers, machineID)
	return err
}

const deleteUserMachineByMachineIDForOwner = `-- name: DeleteUserMachineByMachineIDForOwner :execrows
DELETE FROM user_machines
WHERE machine_id = ?1
  AND user_id = ?2
  AND role = 'owner'
`

type DeleteUserMachineByMachineIDForOwnerParams struct {
	MachineID string
	UserID    string
}

func (q *Queries) DeleteUserMachineByMachineIDForOwner(ctx context.Context, arg DeleteUserMachineByMachineIDForOwnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUserMachineByMachineIDForOwner, arg.MachineID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const enqueueMachineJob = `-- name: EnqueueMachineJob :exec
INSERT INTO machine_jobs (
  id, machine_id, kind, status, attempt, next_run_at, created_at, updated_at
)
VALUES (
  ?1,
  ?2,
  ?3,
  'queued',
  0,
  ?4,
  ?5,
  ?5
)
`

type EnqueueMachineJobParams struct {
	ID        string
	MachineID string
	Kind      string
	NextRunAt int64
	NowUnix   int64
}

func (q *Queries) EnqueueMachineJob(ctx context.Context, arg EnqueueMachineJobParams) error {
	_, err := q.db.ExecContext(ctx, enqueueMachineJob,
		arg.ID,
		arg.MachineID,
		arg.Kind,
		arg.NextRunAt,
		arg.NowUnix,
	)
	return err
}

const getMachineByID = `-- name: GetMachineByID :one
SELECT m.id, m.name, ms.status, ms.desired_status, ms.container_id, ms.last_error
FROM machines m
JOIN machine_states ms ON ms.machine_id = m.id
WHERE m.id = ?1
LIMIT 1
`

type GetMachineByIDRow struct {
	ID            string
	Name          string
	Status        string
	DesiredStatus string
	ContainerID   string
	LastError     string
}

func (q *Queries) GetMachineByID(ctx context.Context, machineID string) (GetMachineByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMachineByID, machineID)
	var i GetMachineByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.DesiredStatus,
		&i.ContainerID,
		&i.LastError,
	)
	return i, err
}

const getMeta = `-- name: GetMeta :one
SELECT value
FROM app_meta
WHERE key = ?1
LIMIT 1
`

func (q *Queries) GetMeta(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getMeta, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getUserByActiveSessionTokenHash = `-- name: GetUserByActiveSessionTokenHash :one
SELECT u.id, u.email, u.password_hash, u.created_at
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = ?1
  AND s.revoked_at IS NULL
  AND s.expires_at > ?2
LIMIT 1
`

type GetUserByActiveSessionTokenHashParams struct {
	TokenHash string
	NowUnix   int64
}

func (q *Queries) GetUserByActiveSessionTokenHash(ctx context.Context, arg GetUserByActiveSessionTokenHashParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByActiveSessionTokenHash, arg.TokenHash, arg.NowUnix)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, created_at
FROM users
WHERE email = ?1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, created_at
FROM users
WHERE id = ?1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const listMachinesByUser = `-- name: ListMachinesByUser :many
SELECT m.id, m.name, ms.status, ms.desired_status, ms.container_id, ms.last_error
FROM machines m
JOIN user_machines um ON um.machine_id = m.id
JOIN machine_states ms ON ms.machine_id = m.id
WHERE um.user_id = ?1
ORDER BY m.created_at DESC
`

type ListMachinesByUserRow struct {
	ID            string
	Name          string
	Status        string
	DesiredStatus string
	ContainerID   string
	LastError     string
}

func (q *Queries) ListMachinesByUser(ctx context.Context, userID string) ([]ListMachinesByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listMachinesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMachinesByUserRow
	for rows.Next() {
		var i ListMachinesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.DesiredStatus,
			&i.ContainerID,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunnableMachineJobs = `-- name: ListRunnableMachineJobs :many
SELECT id, machine_id, kind, attempt
FROM machine_jobs
WHERE status = 'queued'
  AND next_run_at <= ?1
ORDER BY created_at ASC
LIMIT ?2
`

type ListRunnableMachineJobsParams struct {
	NowUnix int64
	LimitN  int64
}

type ListRunnableMachineJobsRow struct {
	ID        string
	MachineID string
	Kind      string
	Attempt   int64
}

func (q *Queries) ListRunnableMachineJobs(ctx context.Context, arg ListRunnableMachineJobsParams) ([]ListRunnableMachineJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRunnableMachineJobs, arg.NowUnix, arg.LimitN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunnableMachineJobsRow
	for rows.Next() {
		var i ListRunnableMachineJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.MachineID,
			&i.Kind,
			&i.Attempt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMachineJobSucceeded = `-- name: MarkMachineJobSucceeded :exec
UPDATE machine_jobs
SET status = 'succeeded',
    lease_owner = NULL,
    lease_until = NULL,
    last_error = NULL,
    updated_at = ?1
WHERE id = ?2
`

type MarkMachineJobSucceededParams struct {
	UpdatedAt int64
	ID        string
}

func (q *Queries) MarkMachineJobSucceeded(ctx context.Context, arg MarkMachineJobSucceededParams) error {
	_, err := q.db.ExecContext(ctx, markMachineJobSucceeded, arg.UpdatedAt, arg.ID)
	return err
}

const recoverExpiredMachineJobs = `-- name: RecoverExpiredMachineJobs :execrows
UPDATE machine_jobs
SET status = 'queued',
    lease_owner = NULL,
    lease_until = NULL,
    updated_at = ?1
WHERE status = 'running'
  AND lease_until IS NOT NULL
  AND lease_until < ?2
`

type RecoverExpiredMachineJobsParams struct {
	UpdatedAt int64
	NowUnix   sql.NullInt64
}

func (q *Queries) RecoverExpiredMachineJobs(ctx context.Context, arg RecoverExpiredMachineJobsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recoverExpiredMachineJobs, arg.UpdatedAt, arg.NowUnix)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const requeueMachineJob = `-- name: RequeueMachineJob :exec
UPDATE machine_jobs
SET status = 'queued',
    attempt = attempt + 1,
    next_run_at = ?1,
    lease_owner = NULL,
    lease_until = NULL,
    last_error = ?2,
    updated_at = ?3
WHERE id = ?4
`

type RequeueMachineJobParams struct {
	NextRunAt int64
	LastError sql.NullString
	UpdatedAt int64
	ID        string
}

func (q *Queries) RequeueMachineJob(ctx context.Context, arg RequeueMachineJobParams) error {
	_, err := q.db.ExecContext(ctx, requeueMachineJob,
		arg.NextRunAt,
		arg.LastError,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const revokeSessionByTokenHash = `-- name: RevokeSessionByTokenHash :exec
UPDATE sessions
SET revoked_at = CURRENT_TIMESTAMP
WHERE token_hash = ?1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, revokeSessionByTokenHash, tokenHash)
	return err
}

const updateMachineNameByIDForOwner = `-- name: UpdateMachineNameByIDForOwner :execrows
UPDATE machines
SET name = ?1
WHERE id = ?2
  AND EXISTS (
    SELECT 1
    FROM user_machines um
    WHERE um.machine_id = machines.id
      AND um.user_id = ?3
      AND um.role = 'owner'
  )
`

type UpdateMachineNameByIDForOwnerParams struct {
	Name      string
	MachineID string
	UserID    string
}

func (q *Queries) UpdateMachineNameByIDForOwner(ctx context.Context, arg UpdateMachineNameByIDForOwnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMachineNameByIDForOwner, arg.Name, arg.MachineID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateMachineRuntimeStateByMachineID = `-- name: UpdateMachineRuntimeStateByMachineID :exec
UPDATE machine_states
SET status = ?1,
    desired_status = ?2,
    container_id = ?3,
    last_error = ?4,
    updated_at = ?5
WHERE machine_id = ?6
`

type UpdateMachineRuntimeStateByMachineIDParams struct {
	Status        string
	DesiredStatus string
	ContainerID   string
	LastError     string
	UpdatedAt     int64
	MachineID     string
}

func (q *Queries) UpdateMachineRuntimeStateByMachineID(ctx context.Context, arg UpdateMachineRuntimeStateByMachineIDParams) error {
	_, err := q.db.ExecContext(ctx, updateMachineRuntimeStateByMachineID,
		arg.Status,
		arg.DesiredStatus,
		arg.ContainerID,
		arg.LastError,
		arg.UpdatedAt,
		arg.MachineID,
	)
	return err
}

const updateMachineStateForOwner = `-- name: UpdateMachineStateForOwner :execrows
UPDATE machine_states
SET status = ?1,
    desired_status = ?2,
    updated_at = ?3,
    last_error = ''
WHERE machine_states.machine_id = ?4
  AND EXISTS (
    SELECT 1
    FROM user_machines um
    WHERE um.machine_id = machine_states.machine_id
      AND um.user_id = ?5
      AND um.role = 'owner'
  )
`

type UpdateMachineStateForOwnerParams struct {
	Status        string
	DesiredStatus string
	UpdatedAt     int64
	MachineID     string
	UserID        string
}

func (q *Queries) UpdateMachineStateForOwner(ctx context.Context, arg UpdateMachineStateForOwnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMachineStateForOwner,
		arg.Status,
		arg.DesiredStatus,
		arg.UpdatedAt,
		arg.MachineID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertMeta = `-- name: UpsertMeta :exec
INSERT INTO app_meta (key, value)
VALUES (?1, ?2)
ON CONFLICT (key) DO UPDATE
SET value = excluded.value
`

type UpsertMetaParams struct {
	Key   string
	Value string
}

func (q *Queries) UpsertMeta(ctx context.Context, arg UpsertMetaParams) error {
	_, err := q.db.ExecContext(ctx, upsertMeta, arg.Key, arg.Value)
	return err
}
