// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgresql

import (
	"database/sql"
	"time"
)

type AppMetum struct {
	Key   string
	Value string
}

type ArcadExchangeToken struct {
	ID         string
	TokenHash  string
	UserID     string
	MachineID  string
	ExposureID string
	ExpiresAt  int64
	UsedAt     sql.NullInt64
	CreatedAt  int64
}

type ArcadSession struct {
	ID          string
	SessionHash string
	UserID      string
	MachineID   string
	ExposureID  string
	ExpiresAt   int64
	RevokedAt   sql.NullInt64
	CreatedAt   int64
}

type AuthTicket struct {
	ID         string
	TicketHash string
	UserID     string
	MachineID  string
	ExposureID string
	ExpiresAt  int64
	UsedAt     sql.NullInt64
	CreatedAt  int64
}

type Machine struct {
	ID           string
	Name         string
	RuntimeID    string
	SetupVersion string
	Endpoint     string
	CreatedAt    time.Time
}

type MachineAccessRequest struct {
	ID               string
	MachineID        string
	UserID           string
	Status           string
	RequestedRole    string
	ResolvedByUserID sql.NullString
	ResolvedRole     string
	Message          string
	CreatedAt        int64
	ResolvedAt       sql.NullInt64
}

type MachineEvent struct {
	ID        string
	MachineID string
	JobID     string
	Level     string
	EventType string
	Message   string
	CreatedAt int64
}

type MachineExposure struct {
	ID        string
	MachineID string
	Name      string
	Hostname  string
	Service   string
	CreatedAt int64
	UpdatedAt int64
}

type MachineGroupAccess struct {
	MachineID string
	GroupID   string
	Role      string
}

type MachineJob struct {
	ID         string
	MachineID  string
	Kind       string
	Status     string
	Attempt    int32
	NextRunAt  int64
	LeaseOwner sql.NullString
	LeaseUntil sql.NullInt64
	LastError  sql.NullString
	CreatedAt  int64
	UpdatedAt  int64
}

type MachineSharing struct {
	MachineID          string
	GeneralAccessScope string
	GeneralAccessRole  string
	UpdatedAt          int64
}

type MachineState struct {
	MachineID       string
	Status          string
	DesiredStatus   string
	ContainerID     string
	LastError       string
	Ready           bool
	ReadyReportedAt int64
	ReadyReason     string
	UpdatedAt       int64
	LastActivityAt  int64
	ArcadVersion    string
}

type MachineToken struct {
	ID        string
	MachineID string
	TokenHash string
	Token     string
	CreatedAt int64
	RevokedAt sql.NullInt64
}

type MachineTunnel struct {
	MachineID   string
	AccountID   string
	TunnelID    string
	TunnelName  string
	TunnelToken string
	CreatedAt   int64
	UpdatedAt   int64
}

type Runtime struct {
	ID         string
	Name       string
	Type       string
	ConfigJson string
	CreatedAt  int64
	UpdatedAt  int64
}

type Session struct {
	ID        string
	UserID    string
	TokenHash string
	ExpiresAt int64
	RevokedAt sql.NullTime
	CreatedAt time.Time
}

type SetupState struct {
	ID                 int32
	Completed          bool
	BaseDomain         string
	DomainPrefix       string
	CloudflareApiToken string
	UpdatedAt          int64
}

type User struct {
	ID                    string
	Email                 string
	PasswordHash          string
	PasswordSetupRequired bool
	Role                  string
	CreatedAt             time.Time
}

type UserGroup struct {
	ID        string
	Name      string
	CreatedAt time.Time
}

type UserGroupMember struct {
	GroupID string
	UserID  string
}

type UserMachine struct {
	UserID    string
	MachineID string
	Role      string
	CreatedAt time.Time
}

type UserNotificationSetting struct {
	UserID       string
	SlackEnabled bool
	SlackUserID  string
	CreatedAt    int64
	UpdatedAt    int64
}

type UserSetting struct {
	UserID            string
	SshPublicKeysJson string
	CreatedAt         int64
	UpdatedAt         int64
}

type UserSetupToken struct {
	ID              string
	TokenHash       string
	UserID          string
	CreatedByUserID sql.NullString
	ExpiresAt       int64
	UsedAt          sql.NullInt64
	CreatedAt       int64
}
