// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgresql

import (
	"database/sql"
	"time"
)

type AppMetum struct {
	Key   string
	Value string
}

type AuthTicket struct {
	ID         string
	TicketHash string
	UserID     string
	MachineID  string
	ExposureID string
	ExpiresAt  int64
	UsedAt     sql.NullInt64
	CreatedAt  int64
}

type Machine struct {
	ID        string
	Name      string
	CreatedAt time.Time
}

type MachineExposure struct {
	ID        string
	MachineID string
	Name      string
	Hostname  string
	Service   string
	IsPublic  bool
	CreatedAt int64
	UpdatedAt int64
}

type MachineJob struct {
	ID         string
	MachineID  string
	Kind       string
	Status     string
	Attempt    int32
	NextRunAt  int64
	LeaseOwner sql.NullString
	LeaseUntil sql.NullInt64
	LastError  sql.NullString
	CreatedAt  int64
	UpdatedAt  int64
}

type MachineState struct {
	MachineID     string
	Status        string
	DesiredStatus string
	ContainerID   string
	LastError     string
	UpdatedAt     int64
}

type MachineToken struct {
	ID        string
	MachineID string
	TokenHash string
	CreatedAt int64
	RevokedAt sql.NullInt64
}

type MachineTunnel struct {
	MachineID   string
	AccountID   string
	TunnelID    string
	TunnelName  string
	TunnelToken string
	CreatedAt   int64
	UpdatedAt   int64
}

type Session struct {
	ID        string
	UserID    string
	TokenHash string
	ExpiresAt int64
	RevokedAt sql.NullTime
	CreatedAt time.Time
}

type SetupState struct {
	ID                    int32
	Completed             bool
	AdminUserID           sql.NullString
	BaseDomain            string
	CloudflareApiToken    string
	DockerProviderEnabled bool
	UpdatedAt             int64
}

type User struct {
	ID           string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
}

type UserMachine struct {
	UserID    string
	MachineID string
	Role      string
	CreatedAt time.Time
}
