// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package postgresql

import (
	"context"
)

const getMeta = `-- name: GetMeta :one
SELECT value
FROM app_meta
WHERE key = $1
LIMIT 1
`

func (q *Queries) GetMeta(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getMeta, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const upsertMeta = `-- name: UpsertMeta :exec
INSERT INTO app_meta (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE
SET value = excluded.value
`

type UpsertMetaParams struct {
	Key   string
	Value string
}

func (q *Queries) UpsertMeta(ctx context.Context, arg UpsertMetaParams) error {
	_, err := q.db.ExecContext(ctx, upsertMeta, arg.Key, arg.Value)
	return err
}
