// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package postgresql

import (
	"context"
	"database/sql"
)

const claimMachineJob = `-- name: ClaimMachineJob :execrows
UPDATE machine_jobs
SET status = 'running',
    lease_owner = $1,
    lease_until = $2,
    updated_at = $3
WHERE id = $4
  AND status = 'queued'
`

type ClaimMachineJobParams struct {
	LeaseOwner sql.NullString
	LeaseUntil sql.NullInt64
	UpdatedAt  int64
	ID         string
}

func (q *Queries) ClaimMachineJob(ctx context.Context, arg ClaimMachineJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimMachineJob,
		arg.LeaseOwner,
		arg.LeaseUntil,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countActiveStartOrReconcileJobsByMachineID = `-- name: CountActiveStartOrReconcileJobsByMachineID :one
SELECT COUNT(1)
FROM machine_jobs
WHERE machine_id = $1
  AND status IN ('queued', 'running')
  AND kind IN ('start', 'reconcile')
`

func (q *Queries) CountActiveStartOrReconcileJobsByMachineID(ctx context.Context, machineID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveStartOrReconcileJobsByMachineID, machineID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArcadExchangeToken = `-- name: CreateArcadExchangeToken :exec
INSERT INTO arcad_exchange_tokens (id, token_hash, user_id, machine_id, exposure_id, expires_at, created_at)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
`

type CreateArcadExchangeTokenParams struct {
	ID         string
	TokenHash  string
	UserID     string
	MachineID  string
	ExposureID string
	ExpiresAt  int64
	CreatedAt  int64
}

func (q *Queries) CreateArcadExchangeToken(ctx context.Context, arg CreateArcadExchangeTokenParams) error {
	_, err := q.db.ExecContext(ctx, createArcadExchangeToken,
		arg.ID,
		arg.TokenHash,
		arg.UserID,
		arg.MachineID,
		arg.ExposureID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const createArcadSession = `-- name: CreateArcadSession :exec
INSERT INTO arcad_sessions (id, session_hash, user_id, machine_id, exposure_id, expires_at, created_at)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
`

type CreateArcadSessionParams struct {
	ID          string
	SessionHash string
	UserID      string
	MachineID   string
	ExposureID  string
	ExpiresAt   int64
	CreatedAt   int64
}

func (q *Queries) CreateArcadSession(ctx context.Context, arg CreateArcadSessionParams) error {
	_, err := q.db.ExecContext(ctx, createArcadSession,
		arg.ID,
		arg.SessionHash,
		arg.UserID,
		arg.MachineID,
		arg.ExposureID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const createAuthTicket = `-- name: CreateAuthTicket :exec
INSERT INTO auth_tickets (id, ticket_hash, user_id, machine_id, exposure_id, expires_at, created_at)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
`

type CreateAuthTicketParams struct {
	ID         string
	TicketHash string
	UserID     string
	MachineID  string
	ExposureID string
	ExpiresAt  int64
	CreatedAt  int64
}

func (q *Queries) CreateAuthTicket(ctx context.Context, arg CreateAuthTicketParams) error {
	_, err := q.db.ExecContext(ctx, createAuthTicket,
		arg.ID,
		arg.TicketHash,
		arg.UserID,
		arg.MachineID,
		arg.ExposureID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const createMachine = `-- name: CreateMachine :exec
INSERT INTO machines (id, name, runtime_id, setup_version)
VALUES ($1, $2, $3, $4)
`

type CreateMachineParams struct {
	ID           string
	Name         string
	RuntimeID    string
	SetupVersion string
}

func (q *Queries) CreateMachine(ctx context.Context, arg CreateMachineParams) error {
	_, err := q.db.ExecContext(ctx, createMachine,
		arg.ID,
		arg.Name,
		arg.RuntimeID,
		arg.SetupVersion,
	)
	return err
}

const createMachineEvent = `-- name: CreateMachineEvent :exec
INSERT INTO machine_events (id, machine_id, job_id, level, event_type, message, created_at)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
`

type CreateMachineEventParams struct {
	ID        string
	MachineID string
	JobID     string
	Level     string
	EventType string
	Message   string
	CreatedAt int64
}

func (q *Queries) CreateMachineEvent(ctx context.Context, arg CreateMachineEventParams) error {
	_, err := q.db.ExecContext(ctx, createMachineEvent,
		arg.ID,
		arg.MachineID,
		arg.JobID,
		arg.Level,
		arg.EventType,
		arg.Message,
		arg.CreatedAt,
	)
	return err
}

const createMachineState = `-- name: CreateMachineState :exec
INSERT INTO machine_states (machine_id, status, desired_status, ready, ready_reported_at, ready_reason, updated_at)
VALUES (
  $1,
  $2,
  $3,
  FALSE,
  $4,
  '',
  $4
)
`

type CreateMachineStateParams struct {
	MachineID     string
	Status        string
	DesiredStatus string
	UpdatedAt     int64
}

func (q *Queries) CreateMachineState(ctx context.Context, arg CreateMachineStateParams) error {
	_, err := q.db.ExecContext(ctx, createMachineState,
		arg.MachineID,
		arg.Status,
		arg.DesiredStatus,
		arg.UpdatedAt,
	)
	return err
}

const createMachineToken = `-- name: CreateMachineToken :exec
INSERT INTO machine_tokens (id, machine_id, token_hash, token, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateMachineTokenParams struct {
	ID        string
	MachineID string
	TokenHash string
	Token     string
	CreatedAt int64
}

func (q *Queries) CreateMachineToken(ctx context.Context, arg CreateMachineTokenParams) error {
	_, err := q.db.ExecContext(ctx, createMachineToken,
		arg.ID,
		arg.MachineID,
		arg.TokenHash,
		arg.Token,
		arg.CreatedAt,
	)
	return err
}

const createRuntime = `-- name: CreateRuntime :exec
INSERT INTO runtimes (id, name, type, config_json, created_at, updated_at)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
`

type CreateRuntimeParams struct {
	ID         string
	Name       string
	Type       string
	ConfigJson string
	CreatedAt  int64
	UpdatedAt  int64
}

func (q *Queries) CreateRuntime(ctx context.Context, arg CreateRuntimeParams) error {
	_, err := q.db.ExecContext(ctx, createRuntime,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.ConfigJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateSessionParams struct {
	ID            string
	UserID        string
	TokenHash     string
	ExpiresAtUnix int64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAtUnix,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, email, password_hash)
VALUES ($1, $2, $3)
`

type CreateUserParams struct {
	ID           string
	Email        string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.ID, arg.Email, arg.PasswordHash)
	return err
}

const createUserMachine = `-- name: CreateUserMachine :exec
INSERT INTO user_machines (user_id, machine_id, role)
VALUES ($1, $2, $3)
`

type CreateUserMachineParams struct {
	UserID    string
	MachineID string
	Role      string
}

func (q *Queries) CreateUserMachine(ctx context.Context, arg CreateUserMachineParams) error {
	_, err := q.db.ExecContext(ctx, createUserMachine, arg.UserID, arg.MachineID, arg.Role)
	return err
}

const createUserSetupToken = `-- name: CreateUserSetupToken :exec
INSERT INTO user_setup_tokens (id, token_hash, user_id, created_by_user_id, expires_at, created_at)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
`

type CreateUserSetupTokenParams struct {
	ID              string
	TokenHash       string
	UserID          string
	CreatedByUserID sql.NullString
	ExpiresAt       int64
	CreatedAt       int64
}

func (q *Queries) CreateUserSetupToken(ctx context.Context, arg CreateUserSetupTokenParams) error {
	_, err := q.db.ExecContext(ctx, createUserSetupToken,
		arg.ID,
		arg.TokenHash,
		arg.UserID,
		arg.CreatedByUserID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteArcadSessionsByUserID = `-- name: DeleteArcadSessionsByUserID :exec
DELETE FROM arcad_sessions
WHERE user_id = $1
`

func (q *Queries) DeleteArcadSessionsByUserID(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteArcadSessionsByUserID, userID)
	return err
}

const deleteMachineByID = `-- name: DeleteMachineByID :execrows
DELETE FROM machines
WHERE id = $1
`

func (q *Queries) DeleteMachineByID(ctx context.Context, machineID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMachineByID, machineID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteMachineExposureACLUsersByExposureID = `-- name: DeleteMachineExposureACLUsersByExposureID :exec
DELETE FROM machine_exposure_acl_users
WHERE exposure_id = $1
`

func (q *Queries) DeleteMachineExposureACLUsersByExposureID(ctx context.Context, exposureID string) error {
	_, err := q.db.ExecContext(ctx, deleteMachineExposureACLUsersByExposureID, exposureID)
	return err
}

const deleteMachineIfNoUsers = `-- name: DeleteMachineIfNoUsers :exec
DELETE FROM machines
WHERE id = $1
  AND NOT EXISTS (
    SELECT 1
    FROM user_machines um
    WHERE um.machine_id = machines.id
  )
`

func (q *Queries) DeleteMachineIfNoUsers(ctx context.Context, machineID string) error {
	_, err := q.db.ExecContext(ctx, deleteMachineIfNoUsers, machineID)
	return err
}

const deleteRuntimeByID = `-- name: DeleteRuntimeByID :execrows
DELETE FROM runtimes
WHERE id = $1
`

func (q *Queries) DeleteRuntimeByID(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRuntimeByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteUserMachineByMachineIDForOwner = `-- name: DeleteUserMachineByMachineIDForOwner :execrows
DELETE FROM user_machines
WHERE machine_id = $1
  AND user_id = $2
  AND role = 'owner'
`

type DeleteUserMachineByMachineIDForOwnerParams struct {
	MachineID string
	UserID    string
}

func (q *Queries) DeleteUserMachineByMachineIDForOwner(ctx context.Context, arg DeleteUserMachineByMachineIDForOwnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUserMachineByMachineIDForOwner, arg.MachineID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const enqueueMachineJob = `-- name: EnqueueMachineJob :exec
INSERT INTO machine_jobs (
  id, machine_id, kind, status, attempt, next_run_at, created_at, updated_at
)
VALUES (
  $1,
  $2,
  $3,
  'queued',
  0,
  $4,
  $5,
  $5
)
`

type EnqueueMachineJobParams struct {
	ID        string
	MachineID string
	Kind      string
	NextRunAt int64
	NowUnix   int64
}

func (q *Queries) EnqueueMachineJob(ctx context.Context, arg EnqueueMachineJobParams) error {
	_, err := q.db.ExecContext(ctx, enqueueMachineJob,
		arg.ID,
		arg.MachineID,
		arg.Kind,
		arg.NextRunAt,
		arg.NowUnix,
	)
	return err
}

const getActiveArcadSessionByHashAndMachine = `-- name: GetActiveArcadSessionByHashAndMachine :one
SELECT s.id, s.user_id, u.email, s.machine_id, s.exposure_id, s.expires_at
FROM arcad_sessions s
JOIN users u ON u.id = s.user_id
WHERE s.session_hash = $1
  AND s.machine_id = $2
  AND s.revoked_at IS NULL
  AND s.expires_at > $3
LIMIT 1
`

type GetActiveArcadSessionByHashAndMachineParams struct {
	SessionHash string
	MachineID   string
	NowUnix     int64
}

type GetActiveArcadSessionByHashAndMachineRow struct {
	ID         string
	UserID     string
	Email      string
	MachineID  string
	ExposureID string
	ExpiresAt  int64
}

func (q *Queries) GetActiveArcadSessionByHashAndMachine(ctx context.Context, arg GetActiveArcadSessionByHashAndMachineParams) (GetActiveArcadSessionByHashAndMachineRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveArcadSessionByHashAndMachine, arg.SessionHash, arg.MachineID, arg.NowUnix)
	var i GetActiveArcadSessionByHashAndMachineRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.MachineID,
		&i.ExposureID,
		&i.ExpiresAt,
	)
	return i, err
}

const getActiveUserSetupTokenByUserID = `-- name: GetActiveUserSetupTokenByUserID :one
SELECT id, token_hash, user_id, created_by_user_id, expires_at, used_at, created_at
FROM user_setup_tokens
WHERE user_id = $1
  AND used_at IS NULL
  AND expires_at > $2
ORDER BY created_at DESC
LIMIT 1
`

type GetActiveUserSetupTokenByUserIDParams struct {
	UserID  string
	NowUnix int64
}

func (q *Queries) GetActiveUserSetupTokenByUserID(ctx context.Context, arg GetActiveUserSetupTokenByUserIDParams) (UserSetupToken, error) {
	row := q.db.QueryRowContext(ctx, getActiveUserSetupTokenByUserID, arg.UserID, arg.NowUnix)
	var i UserSetupToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.CreatedByUserID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getFirstAdminUser = `-- name: GetFirstAdminUser :one
SELECT id, email, role
FROM users
WHERE role = 'admin'
LIMIT 1
`

type GetFirstAdminUserRow struct {
	ID    string
	Email string
	Role  string
}

func (q *Queries) GetFirstAdminUser(ctx context.Context) (GetFirstAdminUserRow, error) {
	row := q.db.QueryRowContext(ctx, getFirstAdminUser)
	var i GetFirstAdminUserRow
	err := row.Scan(&i.ID, &i.Email, &i.Role)
	return i, err
}

const getMachineByID = `-- name: GetMachineByID :one
SELECT m.id, m.name, m.runtime_id, m.setup_version, m.endpoint, ms.status, ms.desired_status, ms.container_id, ms.last_error, ms.ready, ms.ready_reported_at, ms.ready_reason, COALESCE(mt.token, '') AS machine_token
FROM machines m
JOIN machine_states ms ON ms.machine_id = m.id
LEFT JOIN machine_tokens mt ON mt.machine_id = m.id AND mt.revoked_at IS NULL
WHERE m.id = $1
LIMIT 1
`

type GetMachineByIDRow struct {
	ID              string
	Name            string
	RuntimeID       string
	SetupVersion    string
	Endpoint        string
	Status          string
	DesiredStatus   string
	ContainerID     string
	LastError       string
	Ready           bool
	ReadyReportedAt int64
	ReadyReason     string
	MachineToken    string
}

func (q *Queries) GetMachineByID(ctx context.Context, machineID string) (GetMachineByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMachineByID, machineID)
	var i GetMachineByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RuntimeID,
		&i.SetupVersion,
		&i.Endpoint,
		&i.Status,
		&i.DesiredStatus,
		&i.ContainerID,
		&i.LastError,
		&i.Ready,
		&i.ReadyReportedAt,
		&i.ReadyReason,
		&i.MachineToken,
	)
	return i, err
}

const getMachineByIDForUser = `-- name: GetMachineByIDForUser :one
SELECT m.id, m.name, m.runtime_id, m.setup_version, m.endpoint, ms.status, ms.desired_status, ms.container_id, ms.last_error, ms.ready, ms.ready_reported_at, ms.ready_reason
FROM machines m
JOIN machine_states ms ON ms.machine_id = m.id
JOIN user_machines um ON um.machine_id = m.id
WHERE m.id = $1
  AND um.user_id = $2
LIMIT 1
`

type GetMachineByIDForUserParams struct {
	MachineID string
	UserID    string
}

type GetMachineByIDForUserRow struct {
	ID              string
	Name            string
	RuntimeID       string
	SetupVersion    string
	Endpoint        string
	Status          string
	DesiredStatus   string
	ContainerID     string
	LastError       string
	Ready           bool
	ReadyReportedAt int64
	ReadyReason     string
}

func (q *Queries) GetMachineByIDForUser(ctx context.Context, arg GetMachineByIDForUserParams) (GetMachineByIDForUserRow, error) {
	row := q.db.QueryRowContext(ctx, getMachineByIDForUser, arg.MachineID, arg.UserID)
	var i GetMachineByIDForUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RuntimeID,
		&i.SetupVersion,
		&i.Endpoint,
		&i.Status,
		&i.DesiredStatus,
		&i.ContainerID,
		&i.LastError,
		&i.Ready,
		&i.ReadyReportedAt,
		&i.ReadyReason,
	)
	return i, err
}

const getMachineExposureByHostname = `-- name: GetMachineExposureByHostname :one
SELECT id, machine_id, name, hostname, service, is_public, visibility, created_at, updated_at
FROM machine_exposures
WHERE hostname = $1
LIMIT 1
`

func (q *Queries) GetMachineExposureByHostname(ctx context.Context, hostname string) (MachineExposure, error) {
	row := q.db.QueryRowContext(ctx, getMachineExposureByHostname, hostname)
	var i MachineExposure
	err := row.Scan(
		&i.ID,
		&i.MachineID,
		&i.Name,
		&i.Hostname,
		&i.Service,
		&i.IsPublic,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMachineExposureByMachineIDAndName = `-- name: GetMachineExposureByMachineIDAndName :one
SELECT id, machine_id, name, hostname, service, is_public, visibility, created_at, updated_at
FROM machine_exposures
WHERE machine_id = $1
  AND name = $2
LIMIT 1
`

type GetMachineExposureByMachineIDAndNameParams struct {
	MachineID string
	Name      string
}

func (q *Queries) GetMachineExposureByMachineIDAndName(ctx context.Context, arg GetMachineExposureByMachineIDAndNameParams) (MachineExposure, error) {
	row := q.db.QueryRowContext(ctx, getMachineExposureByMachineIDAndName, arg.MachineID, arg.Name)
	var i MachineExposure
	err := row.Scan(
		&i.ID,
		&i.MachineID,
		&i.Name,
		&i.Hostname,
		&i.Service,
		&i.IsPublic,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMachineIDByActiveTokenHash = `-- name: GetMachineIDByActiveTokenHash :one
SELECT machine_id
FROM machine_tokens
WHERE token_hash = $1
  AND revoked_at IS NULL
LIMIT 1
`

func (q *Queries) GetMachineIDByActiveTokenHash(ctx context.Context, tokenHash string) (string, error) {
	row := q.db.QueryRowContext(ctx, getMachineIDByActiveTokenHash, tokenHash)
	var machine_id string
	err := row.Scan(&machine_id)
	return machine_id, err
}

const getMachineOwnerUserID = `-- name: GetMachineOwnerUserID :one
SELECT um.user_id
FROM user_machines um
WHERE um.machine_id = $1
  AND um.role = 'owner'
ORDER BY um.created_at ASC
LIMIT 1
`

func (q *Queries) GetMachineOwnerUserID(ctx context.Context, machineID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getMachineOwnerUserID, machineID)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const getMachineReadinessByMachineID = `-- name: GetMachineReadinessByMachineID :one
SELECT ready, ready_reported_at, desired_status
FROM machine_states
WHERE machine_id = $1
LIMIT 1
`

type GetMachineReadinessByMachineIDRow struct {
	Ready           bool
	ReadyReportedAt int64
	DesiredStatus   string
}

func (q *Queries) GetMachineReadinessByMachineID(ctx context.Context, machineID string) (GetMachineReadinessByMachineIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMachineReadinessByMachineID, machineID)
	var i GetMachineReadinessByMachineIDRow
	err := row.Scan(&i.Ready, &i.ReadyReportedAt, &i.DesiredStatus)
	return i, err
}

const getMachineTunnelByMachineID = `-- name: GetMachineTunnelByMachineID :one
SELECT machine_id, account_id, tunnel_id, tunnel_name, tunnel_token, created_at, updated_at
FROM machine_tunnels
WHERE machine_id = $1
LIMIT 1
`

func (q *Queries) GetMachineTunnelByMachineID(ctx context.Context, machineID string) (MachineTunnel, error) {
	row := q.db.QueryRowContext(ctx, getMachineTunnelByMachineID, machineID)
	var i MachineTunnel
	err := row.Scan(
		&i.MachineID,
		&i.AccountID,
		&i.TunnelID,
		&i.TunnelName,
		&i.TunnelToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMeta = `-- name: GetMeta :one
SELECT value
FROM app_meta
WHERE key = $1
LIMIT 1
`

func (q *Queries) GetMeta(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getMeta, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getRuntimeByID = `-- name: GetRuntimeByID :one
SELECT id, name, type, config_json, created_at, updated_at
FROM runtimes
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetRuntimeByID(ctx context.Context, id string) (Runtime, error) {
	row := q.db.QueryRowContext(ctx, getRuntimeByID, id)
	var i Runtime
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.ConfigJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSetupState = `-- name: GetSetupState :one
SELECT completed, base_domain, domain_prefix, cloudflare_api_token, updated_at
FROM setup_state
WHERE id = 1
LIMIT 1
`

type GetSetupStateRow struct {
	Completed          bool
	BaseDomain         string
	DomainPrefix       string
	CloudflareApiToken string
	UpdatedAt          int64
}

func (q *Queries) GetSetupState(ctx context.Context) (GetSetupStateRow, error) {
	row := q.db.QueryRowContext(ctx, getSetupState)
	var i GetSetupStateRow
	err := row.Scan(
		&i.Completed,
		&i.BaseDomain,
		&i.DomainPrefix,
		&i.CloudflareApiToken,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByActiveSessionTokenHash = `-- name: GetUserByActiveSessionTokenHash :one
SELECT u.id, u.email, u.password_hash, u.password_setup_required, u.role, u.created_at
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1
  AND s.revoked_at IS NULL
  AND s.expires_at > $2
LIMIT 1
`

type GetUserByActiveSessionTokenHashParams struct {
	TokenHash string
	NowUnix   int64
}

func (q *Queries) GetUserByActiveSessionTokenHash(ctx context.Context, arg GetUserByActiveSessionTokenHashParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByActiveSessionTokenHash, arg.TokenHash, arg.NowUnix)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.PasswordSetupRequired,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, password_setup_required, role, created_at
FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.PasswordSetupRequired,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, password_setup_required, role, created_at
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.PasswordSetupRequired,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUserSettingsByUserID = `-- name: GetUserSettingsByUserID :one
SELECT u.id AS user_id,
       COALESCE(s.ssh_public_keys_json, '[]') AS ssh_public_keys_json
FROM users u
LEFT JOIN user_settings s ON s.user_id = u.id
WHERE u.id = $1
LIMIT 1
`

type GetUserSettingsByUserIDRow struct {
	UserID            string
	SshPublicKeysJson string
}

func (q *Queries) GetUserSettingsByUserID(ctx context.Context, userID string) (GetUserSettingsByUserIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserSettingsByUserID, userID)
	var i GetUserSettingsByUserIDRow
	err := row.Scan(&i.UserID, &i.SshPublicKeysJson)
	return i, err
}

const getValidArcadExchangeTokenByHashAndMachine = `-- name: GetValidArcadExchangeTokenByHashAndMachine :one
SELECT t.id, t.user_id, u.email, t.machine_id, t.exposure_id
FROM arcad_exchange_tokens t
JOIN users u ON u.id = t.user_id
WHERE t.token_hash = $1
  AND t.machine_id = $2
  AND t.used_at IS NULL
  AND t.expires_at > $3
LIMIT 1
`

type GetValidArcadExchangeTokenByHashAndMachineParams struct {
	TokenHash string
	MachineID string
	NowUnix   int64
}

type GetValidArcadExchangeTokenByHashAndMachineRow struct {
	ID         string
	UserID     string
	Email      string
	MachineID  string
	ExposureID string
}

func (q *Queries) GetValidArcadExchangeTokenByHashAndMachine(ctx context.Context, arg GetValidArcadExchangeTokenByHashAndMachineParams) (GetValidArcadExchangeTokenByHashAndMachineRow, error) {
	row := q.db.QueryRowContext(ctx, getValidArcadExchangeTokenByHashAndMachine, arg.TokenHash, arg.MachineID, arg.NowUnix)
	var i GetValidArcadExchangeTokenByHashAndMachineRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.MachineID,
		&i.ExposureID,
	)
	return i, err
}

const getValidAuthTicketByHashAndMachine = `-- name: GetValidAuthTicketByHashAndMachine :one
SELECT t.id, t.user_id, u.email, t.machine_id, t.exposure_id
FROM auth_tickets t
JOIN users u ON u.id = t.user_id
WHERE t.ticket_hash = $1
  AND t.machine_id = $2
  AND t.used_at IS NULL
  AND t.expires_at > $3
LIMIT 1
`

type GetValidAuthTicketByHashAndMachineParams struct {
	TicketHash string
	MachineID  string
	NowUnix    int64
}

type GetValidAuthTicketByHashAndMachineRow struct {
	ID         string
	UserID     string
	Email      string
	MachineID  string
	ExposureID string
}

func (q *Queries) GetValidAuthTicketByHashAndMachine(ctx context.Context, arg GetValidAuthTicketByHashAndMachineParams) (GetValidAuthTicketByHashAndMachineRow, error) {
	row := q.db.QueryRowContext(ctx, getValidAuthTicketByHashAndMachine, arg.TicketHash, arg.MachineID, arg.NowUnix)
	var i GetValidAuthTicketByHashAndMachineRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.MachineID,
		&i.ExposureID,
	)
	return i, err
}

const getValidUserSetupTokenByHash = `-- name: GetValidUserSetupTokenByHash :one
SELECT t.id, t.token_hash, t.user_id, t.created_by_user_id, t.expires_at, t.used_at, t.created_at, u.email
FROM user_setup_tokens t
JOIN users u ON u.id = t.user_id
WHERE t.token_hash = $1
  AND t.used_at IS NULL
  AND t.expires_at > $2
LIMIT 1
`

type GetValidUserSetupTokenByHashParams struct {
	TokenHash string
	NowUnix   int64
}

type GetValidUserSetupTokenByHashRow struct {
	ID              string
	TokenHash       string
	UserID          string
	CreatedByUserID sql.NullString
	ExpiresAt       int64
	UsedAt          sql.NullInt64
	CreatedAt       int64
	Email           string
}

func (q *Queries) GetValidUserSetupTokenByHash(ctx context.Context, arg GetValidUserSetupTokenByHashParams) (GetValidUserSetupTokenByHashRow, error) {
	row := q.db.QueryRowContext(ctx, getValidUserSetupTokenByHash, arg.TokenHash, arg.NowUnix)
	var i GetValidUserSetupTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.CreatedByUserID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
		&i.Email,
	)
	return i, err
}

const hasAdminUser = `-- name: HasAdminUser :one
SELECT COUNT(1) > 0
FROM users
WHERE role = 'admin'
LIMIT 1
`

func (q *Queries) HasAdminUser(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasAdminUser)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const insertMachineExposureACLUser = `-- name: InsertMachineExposureACLUser :exec
INSERT INTO machine_exposure_acl_users (exposure_id, user_id, created_at)
VALUES ($1, $2, $3)
ON CONFLICT (exposure_id, user_id) DO NOTHING
`

type InsertMachineExposureACLUserParams struct {
	ExposureID string
	UserID     string
	CreatedAt  int64
}

func (q *Queries) InsertMachineExposureACLUser(ctx context.Context, arg InsertMachineExposureACLUserParams) error {
	_, err := q.db.ExecContext(ctx, insertMachineExposureACLUser, arg.ExposureID, arg.UserID, arg.CreatedAt)
	return err
}

const invalidateUserSetupTokensByUserID = `-- name: InvalidateUserSetupTokensByUserID :exec
UPDATE user_setup_tokens
SET used_at = $1
WHERE user_id = $2
  AND used_at IS NULL
`

type InvalidateUserSetupTokensByUserIDParams struct {
	UsedAt sql.NullInt64
	UserID string
}

func (q *Queries) InvalidateUserSetupTokensByUserID(ctx context.Context, arg InvalidateUserSetupTokensByUserIDParams) error {
	_, err := q.db.ExecContext(ctx, invalidateUserSetupTokensByUserID, arg.UsedAt, arg.UserID)
	return err
}

const listMachineEventsByMachineIDForUser = `-- name: ListMachineEventsByMachineIDForUser :many
SELECT me.id, me.machine_id, me.job_id, me.level, me.event_type, me.message, me.created_at
FROM machine_events me
JOIN user_machines um ON um.machine_id = me.machine_id
WHERE me.machine_id = $1
  AND um.user_id = $2
ORDER BY me.created_at DESC
LIMIT $3
`

type ListMachineEventsByMachineIDForUserParams struct {
	MachineID string
	UserID    string
	LimitN    int32
}

func (q *Queries) ListMachineEventsByMachineIDForUser(ctx context.Context, arg ListMachineEventsByMachineIDForUserParams) ([]MachineEvent, error) {
	rows, err := q.db.QueryContext(ctx, listMachineEventsByMachineIDForUser, arg.MachineID, arg.UserID, arg.LimitN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MachineEvent
	for rows.Next() {
		var i MachineEvent
		if err := rows.Scan(
			&i.ID,
			&i.MachineID,
			&i.JobID,
			&i.Level,
			&i.EventType,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMachineExposureACLUsersByExposureID = `-- name: ListMachineExposureACLUsersByExposureID :many
SELECT user_id
FROM machine_exposure_acl_users
WHERE exposure_id = $1
ORDER BY user_id ASC
`

func (q *Queries) ListMachineExposureACLUsersByExposureID(ctx context.Context, exposureID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listMachineExposureACLUsersByExposureID, exposureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMachineExposuresByMachineID = `-- name: ListMachineExposuresByMachineID :many
SELECT id, machine_id, name, hostname, service, is_public, visibility, created_at, updated_at
FROM machine_exposures
WHERE machine_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListMachineExposuresByMachineID(ctx context.Context, machineID string) ([]MachineExposure, error) {
	rows, err := q.db.QueryContext(ctx, listMachineExposuresByMachineID, machineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MachineExposure
	for rows.Next() {
		var i MachineExposure
		if err := rows.Scan(
			&i.ID,
			&i.MachineID,
			&i.Name,
			&i.Hostname,
			&i.Service,
			&i.IsPublic,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMachinesByDesiredStatus = `-- name: ListMachinesByDesiredStatus :many
SELECT m.id, m.name, m.runtime_id, m.setup_version, m.endpoint, ms.status, ms.desired_status, ms.container_id, ms.last_error, ms.ready, ms.ready_reported_at, ms.ready_reason
FROM machines m
JOIN machine_states ms ON ms.machine_id = m.id
WHERE ms.desired_status = $1
ORDER BY ms.updated_at ASC
LIMIT $2
`

type ListMachinesByDesiredStatusParams struct {
	DesiredStatus string
	LimitN        int32
}

type ListMachinesByDesiredStatusRow struct {
	ID              string
	Name            string
	RuntimeID       string
	SetupVersion    string
	Endpoint        string
	Status          string
	DesiredStatus   string
	ContainerID     string
	LastError       string
	Ready           bool
	ReadyReportedAt int64
	ReadyReason     string
}

func (q *Queries) ListMachinesByDesiredStatus(ctx context.Context, arg ListMachinesByDesiredStatusParams) ([]ListMachinesByDesiredStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, listMachinesByDesiredStatus, arg.DesiredStatus, arg.LimitN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMachinesByDesiredStatusRow
	for rows.Next() {
		var i ListMachinesByDesiredStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RuntimeID,
			&i.SetupVersion,
			&i.Endpoint,
			&i.Status,
			&i.DesiredStatus,
			&i.ContainerID,
			&i.LastError,
			&i.Ready,
			&i.ReadyReportedAt,
			&i.ReadyReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMachinesByUser = `-- name: ListMachinesByUser :many
SELECT m.id, m.name, m.runtime_id, m.setup_version, m.endpoint, ms.status, ms.desired_status, ms.container_id, ms.last_error, ms.ready, ms.ready_reported_at, ms.ready_reason
FROM machines m
JOIN user_machines um ON um.machine_id = m.id
JOIN machine_states ms ON ms.machine_id = m.id
WHERE um.user_id = $1
ORDER BY m.created_at DESC
`

type ListMachinesByUserRow struct {
	ID              string
	Name            string
	RuntimeID       string
	SetupVersion    string
	Endpoint        string
	Status          string
	DesiredStatus   string
	ContainerID     string
	LastError       string
	Ready           bool
	ReadyReportedAt int64
	ReadyReason     string
}

func (q *Queries) ListMachinesByUser(ctx context.Context, userID string) ([]ListMachinesByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listMachinesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMachinesByUserRow
	for rows.Next() {
		var i ListMachinesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RuntimeID,
			&i.SetupVersion,
			&i.Endpoint,
			&i.Status,
			&i.DesiredStatus,
			&i.ContainerID,
			&i.LastError,
			&i.Ready,
			&i.ReadyReportedAt,
			&i.ReadyReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunnableMachineJobs = `-- name: ListRunnableMachineJobs :many
SELECT id, machine_id, kind, attempt
FROM machine_jobs
WHERE status = 'queued'
  AND next_run_at <= $1
ORDER BY created_at ASC
LIMIT $2
`

type ListRunnableMachineJobsParams struct {
	NowUnix int64
	LimitN  int32
}

type ListRunnableMachineJobsRow struct {
	ID        string
	MachineID string
	Kind      string
	Attempt   int32
}

func (q *Queries) ListRunnableMachineJobs(ctx context.Context, arg ListRunnableMachineJobsParams) ([]ListRunnableMachineJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRunnableMachineJobs, arg.NowUnix, arg.LimitN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunnableMachineJobsRow
	for rows.Next() {
		var i ListRunnableMachineJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.MachineID,
			&i.Kind,
			&i.Attempt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuntimes = `-- name: ListRuntimes :many
SELECT id, name, type, config_json, created_at, updated_at
FROM runtimes
ORDER BY created_at ASC
`

func (q *Queries) ListRuntimes(ctx context.Context) ([]Runtime, error) {
	rows, err := q.db.QueryContext(ctx, listRuntimes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Runtime
	for rows.Next() {
		var i Runtime
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.ConfigJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, password_setup_required, role, created_at
FROM users
ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.PasswordSetupRequired,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markArcadExchangeTokenUsed = `-- name: MarkArcadExchangeTokenUsed :execrows
UPDATE arcad_exchange_tokens
SET used_at = $1
WHERE id = $2
  AND used_at IS NULL
`

type MarkArcadExchangeTokenUsedParams struct {
	UsedAt sql.NullInt64
	ID     string
}

func (q *Queries) MarkArcadExchangeTokenUsed(ctx context.Context, arg MarkArcadExchangeTokenUsedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markArcadExchangeTokenUsed, arg.UsedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markAuthTicketUsed = `-- name: MarkAuthTicketUsed :execrows
UPDATE auth_tickets
SET used_at = $1
WHERE id = $2
  AND used_at IS NULL
`

type MarkAuthTicketUsedParams struct {
	UsedAt sql.NullInt64
	ID     string
}

func (q *Queries) MarkAuthTicketUsed(ctx context.Context, arg MarkAuthTicketUsedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markAuthTicketUsed, arg.UsedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markMachineJobSucceeded = `-- name: MarkMachineJobSucceeded :exec
UPDATE machine_jobs
SET status = 'succeeded',
    lease_owner = NULL,
    lease_until = NULL,
    last_error = NULL,
    updated_at = $1
WHERE id = $2
`

type MarkMachineJobSucceededParams struct {
	UpdatedAt int64
	ID        string
}

func (q *Queries) MarkMachineJobSucceeded(ctx context.Context, arg MarkMachineJobSucceededParams) error {
	_, err := q.db.ExecContext(ctx, markMachineJobSucceeded, arg.UpdatedAt, arg.ID)
	return err
}

const markUserSetupTokenUsed = `-- name: MarkUserSetupTokenUsed :execrows
UPDATE user_setup_tokens
SET used_at = $1
WHERE id = $2
  AND used_at IS NULL
`

type MarkUserSetupTokenUsedParams struct {
	UsedAt sql.NullInt64
	ID     string
}

func (q *Queries) MarkUserSetupTokenUsed(ctx context.Context, arg MarkUserSetupTokenUsedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markUserSetupTokenUsed, arg.UsedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recoverExpiredMachineJobs = `-- name: RecoverExpiredMachineJobs :execrows
UPDATE machine_jobs
SET status = 'queued',
    lease_owner = NULL,
    lease_until = NULL,
    updated_at = $1
WHERE status = 'running'
  AND lease_until IS NOT NULL
  AND lease_until < $2
`

type RecoverExpiredMachineJobsParams struct {
	UpdatedAt int64
	NowUnix   sql.NullInt64
}

func (q *Queries) RecoverExpiredMachineJobs(ctx context.Context, arg RecoverExpiredMachineJobsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recoverExpiredMachineJobs, arg.UpdatedAt, arg.NowUnix)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const reportMachineReadinessByMachineID = `-- name: ReportMachineReadinessByMachineID :execrows
UPDATE machine_states
SET ready = $1,
    ready_reported_at = $2,
    ready_reason = $3,
    container_id = CASE
      WHEN $4 <> '' THEN $4
      ELSE container_id
    END,
    status = CASE
      WHEN $1 = TRUE
        AND desired_status = 'running'
        AND status IN ('pending', 'starting', 'running')
      THEN 'running'
      ELSE status
    END,
    last_error = CASE
      WHEN $1 = TRUE
        AND desired_status = 'running'
      THEN ''
      ELSE last_error
    END,
    updated_at = $5
WHERE machine_id = $6
  AND (
    $1 = FALSE
    OR desired_status = 'running'
  )
`

type ReportMachineReadinessByMachineIDParams struct {
	Ready           bool
	ReadyReportedAt int64
	ReadyReason     string
	ContainerID     interface{}
	UpdatedAt       int64
	MachineID       string
}

func (q *Queries) ReportMachineReadinessByMachineID(ctx context.Context, arg ReportMachineReadinessByMachineIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reportMachineReadinessByMachineID,
		arg.Ready,
		arg.ReadyReportedAt,
		arg.ReadyReason,
		arg.ContainerID,
		arg.UpdatedAt,
		arg.MachineID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const requeueMachineJob = `-- name: RequeueMachineJob :exec
UPDATE machine_jobs
SET status = 'queued',
    attempt = attempt + 1,
    next_run_at = $1,
    lease_owner = NULL,
    lease_until = NULL,
    last_error = $2,
    updated_at = $3
WHERE id = $4
`

type RequeueMachineJobParams struct {
	NextRunAt int64
	LastError sql.NullString
	UpdatedAt int64
	ID        string
}

func (q *Queries) RequeueMachineJob(ctx context.Context, arg RequeueMachineJobParams) error {
	_, err := q.db.ExecContext(ctx, requeueMachineJob,
		arg.NextRunAt,
		arg.LastError,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const revokeArcadSessionByHash = `-- name: RevokeArcadSessionByHash :exec
UPDATE arcad_sessions
SET revoked_at = $1
WHERE session_hash = $2
  AND revoked_at IS NULL
`

type RevokeArcadSessionByHashParams struct {
	RevokedAt   sql.NullInt64
	SessionHash string
}

func (q *Queries) RevokeArcadSessionByHash(ctx context.Context, arg RevokeArcadSessionByHashParams) error {
	_, err := q.db.ExecContext(ctx, revokeArcadSessionByHash, arg.RevokedAt, arg.SessionHash)
	return err
}

const revokeSessionByTokenHash = `-- name: RevokeSessionByTokenHash :exec
UPDATE sessions
SET revoked_at = CURRENT_TIMESTAMP
WHERE token_hash = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, revokeSessionByTokenHash, tokenHash)
	return err
}

const updateMachineEndpointByID = `-- name: UpdateMachineEndpointByID :exec
UPDATE machines
SET endpoint = $1
WHERE id = $2
`

type UpdateMachineEndpointByIDParams struct {
	Endpoint  string
	MachineID string
}

func (q *Queries) UpdateMachineEndpointByID(ctx context.Context, arg UpdateMachineEndpointByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateMachineEndpointByID, arg.Endpoint, arg.MachineID)
	return err
}

const updateMachineNameByIDForOwner = `-- name: UpdateMachineNameByIDForOwner :execrows
UPDATE machines
SET name = $1
WHERE id = $2
  AND EXISTS (
    SELECT 1
    FROM user_machines um
    WHERE um.machine_id = machines.id
      AND um.user_id = $3
      AND um.role = 'owner'
  )
`

type UpdateMachineNameByIDForOwnerParams struct {
	Name      string
	MachineID string
	UserID    string
}

func (q *Queries) UpdateMachineNameByIDForOwner(ctx context.Context, arg UpdateMachineNameByIDForOwnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMachineNameByIDForOwner, arg.Name, arg.MachineID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateMachineRuntimeByIDForOwner = `-- name: UpdateMachineRuntimeByIDForOwner :execrows
UPDATE machines
SET runtime_id = $1,
    setup_version = $2
WHERE id = $3
  AND EXISTS (
    SELECT 1
    FROM user_machines um
    WHERE um.machine_id = machines.id
      AND um.user_id = $4
      AND um.role = 'owner'
  )
`

type UpdateMachineRuntimeByIDForOwnerParams struct {
	RuntimeID    string
	SetupVersion string
	MachineID    string
	UserID       string
}

func (q *Queries) UpdateMachineRuntimeByIDForOwner(ctx context.Context, arg UpdateMachineRuntimeByIDForOwnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMachineRuntimeByIDForOwner,
		arg.RuntimeID,
		arg.SetupVersion,
		arg.MachineID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateMachineRuntimeStateByMachineID = `-- name: UpdateMachineRuntimeStateByMachineID :exec
UPDATE machine_states
SET status = $1,
    desired_status = $2,
    container_id = $3,
    last_error = $4,
    updated_at = $5
WHERE machine_id = $6
`

type UpdateMachineRuntimeStateByMachineIDParams struct {
	Status        string
	DesiredStatus string
	ContainerID   string
	LastError     string
	UpdatedAt     int64
	MachineID     string
}

func (q *Queries) UpdateMachineRuntimeStateByMachineID(ctx context.Context, arg UpdateMachineRuntimeStateByMachineIDParams) error {
	_, err := q.db.ExecContext(ctx, updateMachineRuntimeStateByMachineID,
		arg.Status,
		arg.DesiredStatus,
		arg.ContainerID,
		arg.LastError,
		arg.UpdatedAt,
		arg.MachineID,
	)
	return err
}

const updateMachineStateForOwner = `-- name: UpdateMachineStateForOwner :execrows
UPDATE machine_states
SET status = $1,
    desired_status = $2,
    updated_at = $3,
    last_error = '',
    ready = FALSE,
    ready_reported_at = $3,
    ready_reason = 'state transition requested'
WHERE machine_states.machine_id = $4
  AND EXISTS (
    SELECT 1
    FROM user_machines um
    WHERE um.machine_id = machine_states.machine_id
      AND um.user_id = $5
      AND um.role = 'owner'
  )
`

type UpdateMachineStateForOwnerParams struct {
	Status        string
	DesiredStatus string
	UpdatedAt     int64
	MachineID     string
	UserID        string
}

func (q *Queries) UpdateMachineStateForOwner(ctx context.Context, arg UpdateMachineStateForOwnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMachineStateForOwner,
		arg.Status,
		arg.DesiredStatus,
		arg.UpdatedAt,
		arg.MachineID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateRuntimeByID = `-- name: UpdateRuntimeByID :execrows
UPDATE runtimes
SET name = $1,
    type = $2,
    config_json = $3,
    updated_at = $4
WHERE id = $5
`

type UpdateRuntimeByIDParams struct {
	Name       string
	Type       string
	ConfigJson string
	UpdatedAt  int64
	ID         string
}

func (q *Queries) UpdateRuntimeByID(ctx context.Context, arg UpdateRuntimeByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateRuntimeByID,
		arg.Name,
		arg.Type,
		arg.ConfigJson,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateUserPasswordHashByID = `-- name: UpdateUserPasswordHashByID :execrows
UPDATE users
SET password_hash = $1
WHERE id = $2
`

type UpdateUserPasswordHashByIDParams struct {
	PasswordHash string
	ID           string
}

func (q *Queries) UpdateUserPasswordHashByID(ctx context.Context, arg UpdateUserPasswordHashByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUserPasswordHashByID, arg.PasswordHash, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateUserPasswordSetupRequiredByID = `-- name: UpdateUserPasswordSetupRequiredByID :execrows
UPDATE users
SET password_setup_required = $1
WHERE id = $2
`

type UpdateUserPasswordSetupRequiredByIDParams struct {
	PasswordSetupRequired bool
	ID                    string
}

func (q *Queries) UpdateUserPasswordSetupRequiredByID(ctx context.Context, arg UpdateUserPasswordSetupRequiredByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUserPasswordSetupRequiredByID, arg.PasswordSetupRequired, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateUserRoleByID = `-- name: UpdateUserRoleByID :execrows
UPDATE users
SET role = $1
WHERE id = $2
`

type UpdateUserRoleByIDParams struct {
	Role string
	ID   string
}

func (q *Queries) UpdateUserRoleByID(ctx context.Context, arg UpdateUserRoleByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUserRoleByID, arg.Role, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertMachineExposure = `-- name: UpsertMachineExposure :exec
INSERT INTO machine_exposures (id, machine_id, name, hostname, service, is_public, visibility, created_at, updated_at)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9
)
ON CONFLICT (machine_id, name) DO UPDATE
SET hostname = excluded.hostname,
    service = excluded.service,
    is_public = excluded.is_public,
    visibility = excluded.visibility,
    updated_at = excluded.updated_at
`

type UpsertMachineExposureParams struct {
	ID         string
	MachineID  string
	Name       string
	Hostname   string
	Service    string
	IsPublic   bool
	Visibility string
	CreatedAt  int64
	UpdatedAt  int64
}

func (q *Queries) UpsertMachineExposure(ctx context.Context, arg UpsertMachineExposureParams) error {
	_, err := q.db.ExecContext(ctx, upsertMachineExposure,
		arg.ID,
		arg.MachineID,
		arg.Name,
		arg.Hostname,
		arg.Service,
		arg.IsPublic,
		arg.Visibility,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertMachineTunnel = `-- name: UpsertMachineTunnel :exec
INSERT INTO machine_tunnels (machine_id, account_id, tunnel_id, tunnel_name, tunnel_token, created_at, updated_at)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
ON CONFLICT (machine_id) DO UPDATE
SET account_id = excluded.account_id,
    tunnel_id = excluded.tunnel_id,
    tunnel_name = excluded.tunnel_name,
    tunnel_token = excluded.tunnel_token,
    updated_at = excluded.updated_at
`

type UpsertMachineTunnelParams struct {
	MachineID   string
	AccountID   string
	TunnelID    string
	TunnelName  string
	TunnelToken string
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) UpsertMachineTunnel(ctx context.Context, arg UpsertMachineTunnelParams) error {
	_, err := q.db.ExecContext(ctx, upsertMachineTunnel,
		arg.MachineID,
		arg.AccountID,
		arg.TunnelID,
		arg.TunnelName,
		arg.TunnelToken,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertMeta = `-- name: UpsertMeta :exec
INSERT INTO app_meta (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE
SET value = excluded.value
`

type UpsertMetaParams struct {
	Key   string
	Value string
}

func (q *Queries) UpsertMeta(ctx context.Context, arg UpsertMetaParams) error {
	_, err := q.db.ExecContext(ctx, upsertMeta, arg.Key, arg.Value)
	return err
}

const upsertSetupState = `-- name: UpsertSetupState :exec
INSERT INTO setup_state (id, completed, base_domain, domain_prefix, cloudflare_api_token, updated_at)
VALUES (
  1,
  $1,
  $2,
  $3,
  $4,
  $5
)
ON CONFLICT (id) DO UPDATE
SET completed = excluded.completed,
    base_domain = excluded.base_domain,
    domain_prefix = excluded.domain_prefix,
    cloudflare_api_token = excluded.cloudflare_api_token,
    updated_at = excluded.updated_at
`

type UpsertSetupStateParams struct {
	Completed          bool
	BaseDomain         string
	DomainPrefix       string
	CloudflareApiToken string
	UpdatedAt          int64
}

func (q *Queries) UpsertSetupState(ctx context.Context, arg UpsertSetupStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetupState,
		arg.Completed,
		arg.BaseDomain,
		arg.DomainPrefix,
		arg.CloudflareApiToken,
		arg.UpdatedAt,
	)
	return err
}

const upsertUserSettingsByUserID = `-- name: UpsertUserSettingsByUserID :exec
INSERT INTO user_settings (user_id, ssh_public_keys_json, created_at, updated_at)
VALUES (
  $1,
  $2,
  $3,
  $4
)
ON CONFLICT (user_id) DO UPDATE
SET ssh_public_keys_json = excluded.ssh_public_keys_json,
    updated_at = excluded.updated_at
`

type UpsertUserSettingsByUserIDParams struct {
	UserID            string
	SshPublicKeysJson string
	CreatedAt         int64
	UpdatedAt         int64
}

func (q *Queries) UpsertUserSettingsByUserID(ctx context.Context, arg UpsertUserSettingsByUserIDParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserSettingsByUserID,
		arg.UserID,
		arg.SshPublicKeysJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
